<?php

namespace sf_moocms\MoocmsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use sf_moocms\UserBundle\Entity\User;
use sf_moocms\MoocmsBundle\Entity\Activity;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
	public function createAlphabeticalQueryBuilder()
  {
    return $this->createQueryBuilder('activity')
    ->orderBy('activity.title', 'ASC');
  }

  public function getCurrentUserActivities(User $user){
  	
  	return $this->createQueryBuilder('activity')
   ->where('activity.user=:owner')
   ->setParameter('owner', $user);
  }
  
}
