<?php

namespace sf_moocms\MoocmsBundle\Repository;

use sf_moocms\MoocmsBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
