<?php

namespace sf_moocms\MoocmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

use sf_moocms\MoocmsBundle\Entity\CourseLesson;
use sf_moocms\MoocmsBundle\Entity\Course;

/**
 * CourseLessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseLessonRepository extends EntityRepository
{
	public function getNbForCourse(Course $course) {

		$qb = $this->createQueryBuilder('s')
		->select('COUNT(s)')
		->where('s.course = :id')
		->setParameter('id', $course);

		return $qb->getQuery()
		->getSingleScalarResult();

	}

	public function update_positions(CourseLesson $course_lesson) {

		$qb = $this->createQueryBuilder('s')
		->update('sf_moocms\MoocmsBundle\Entity\CourseLesson','s')
		->set('s.position','s.position - 1')
		->where('s.position > :rem_pos')
		->andWhere('s.course = :course')
		->setParameter('rem_pos',$course_lesson->getPosition())
		->setParameter('course',$course_lesson->getCourse())
		;

		return $qb->getQuery()
		->execute();
	}
}
