<?php

namespace sf_moocms\MoocmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

use sf_moocms\MoocmsBundle\Entity\Lesson;
use sf_moocms\MoocmsBundle\Entity\LessonSearch;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends EntityRepository
{
	public function getLast($nb) {

		$qb = $this->createQueryBuilder('s')
			->setMaxResults($nb)
			->orderBy('s.id', 'DESC');
			// ->setParameter('nb', $nb)

		return $qb->getQuery()
			->getResult();
	}

	/**
	 * Retourne les leçons qui ne font  par partie du cours
	 * @param integer
	 * @return array()
	 *
	 */

	public function getNotUsedLessons($course_id){

		$qb = $this->createQueryBuilder('s');

		$qb2 = $qb;
		
		  $qb2->select('identity(ms.lesson)')
					->from('sf_moocms\MoocmsBundle\Entity\CourseLesson','ms')
					->where('ms.course = :course_id')					
			;
			

		$qb= $this->createQueryBuilder('ss')
			->where($qb->expr()->notIn('ss.id', $qb2->getDQL()))
			// ->where('ss.id','not in',$qb2)
			->setParameter('course_id', $course_id)
			;

			return $qb->getQuery()
			->getResult();

			//"select * from lesson where id not in(select lesson_id from course_lesson where course_id = 1)"
	}

	/**
	 * Retourne les leçons qui ne font  par partie du cours
	 * @param integer
	 * @return array()
	 *
	 */

	public function getNotUsedLessonsByUser($course_id, $user_id){

		$qb = $this->createQueryBuilder('s');

		$qb2 = $qb;
		
		  $qb2->select('identity(ms.lesson)')
					->from('sf_moocms\MoocmsBundle\Entity\CourseLesson','ms')
					->where('ms.course = :course_id')									
			;			

		$qb= $this->createQueryBuilder('ss')
			->where($qb->expr()->notIn('ss.id', $qb2->getDQL()))
			->andwhere('ss.user = :user_id')	
			->setParameters(array('course_id' => $course_id, ':user_id' => $user_id));
			;

			return $qb->getQuery()
			->getResult();

			//"select * from lesson where id not in(select lesson_id from course_lesson where course_id = 1)"
	}

	// public function getAllOrdered(CourseLesson $courseLesson) {

	// 	$qb = $this->createQueryBuilder('s')
	// 		->where('s.courseLessons = :id')			
	// 		->orderBy('s.number', 'ASC')
	// 		->setParameter('id', $lesson);

	// 	return $qb->getQuery()
	// 		->getResult();
	// }

  // public function findAllQuery() {
  //   return $this->createQueryBuilder('a')
  //   ->andWhere("a.published = true")
  //   ->orWhere("a.promote = true")
  //   ->getQuery();

  // }

  public function findAllRequestedQuery(LessonSearch $search) {
    $query = $this->createQueryBuilder('a')
    		->andWhere("a.published = true")
            ->orWhere("a.promote = true");

    if($search->getCategories() && $search->getCategories()->count() > 0){
        foreach ($search->getCategories() as $k => $category) {
          $query = $query
            ->andWhere(":category MEMBER OF a.categories")
            
            ->setParameter("category", $category);
        }
      }

      if($search->getTopic()){
          $query = $query
            ->andWhere(":topic = a.topic")
            ->setParameter("topic", $search->getTopic());
      }

    return $query->getQuery();

  }

}
