<?php

namespace sf_moocms\MoocmsBundle\Repository;

/**
 * SearchLessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchLessonRepository extends \Doctrine\ORM\EntityRepository
{
}
