<?php

namespace sf_moocms\MoocmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

use sf_moocms\MoocmsBundle\Entity\Sequence;
use sf_moocms\MoocmsBundle\Entity\Lesson;

/**
 * SequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequenceRepository extends EntityRepository
{
	public function getNb() {

		$qb = $this->createQueryBuilder('s')
			->select('COUNT(s)');

		return $qb->getQuery()
			->getSingleScalarResult();

	}

	public function getNbForLesson(Lesson $lesson) {

		$qb = $this->createQueryBuilder('s')
			->select('COUNT(s)')
			->where('s.lesson = :id')
			->setParameter('id', $lesson);

		return $qb->getQuery()
			->getSingleScalarResult();

	}

	public function getAllOrdered(Lesson $lesson) {

		$qb = $this->createQueryBuilder('s')
			->where('s.lesson = :id')			
			->orderBy('s.number', 'ASC')
			->setParameter('id', $lesson);

		return $qb->getQuery()
			->getResult();
	}
}
