<?php

namespace sf_moocms\MoocmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

use sf_moocms\MoocmsBundle\Entity\Topic;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{
}
