<?php

namespace sf_moocms\MoocmsBundle\Repository;

use sf_moocms\MoocmsBundle\Entity\Lesson;

/**
* BookRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class LessonRepository extends \Doctrine\ORM\EntityRepository
{

  public function findByCategories($categories){

    $query = $this->createQueryBuilder('a')
    ->select('a')
    ->leftJoin('a.categories', 'c')
    ->addSelect('c');

    $query = $query->add('where', $query->expr()->in('c', ':c'))
    ->setParameter('c', $categories)
    ->getQuery()
    ->getResult();

    return $query;
  }

  public function xfindAllQuery() {
    return $this->createQueryBuilder('a')
    ->getQuery();

  }
}